Try again to reduce container size

diff --git a/Dockerfile.new b/Dockerfile.new
--- a/Dockerfile.new
+++ b/Dockerfile.new
@@ -19,31 +19,37 @@ RUN mv inputs inputs.bak \
       && tar -zxvf latest.tar.gz \
       && mv test-data-latest/${PLATFORM}/* ./ \
       && wget https://github.com/EHSRB-BSRSE-Bioinformatics/unify_temposeq_manifests/raw/main/output_manifests/Human_S1500_1.2_standardized.csv \
-      && rm latest.tar.gz \
-      && df -h
+      && rm latest.tar.gz
 
 # Build environments with Snakemake
 RUN snakemake --cores ${BUILD_CORES} --software-deployment-method conda --conda-create-envs-only 
 
 # Install extra dependency for reports
-RUN mamba run -p $(grep -rl "R-ODAF_reports" .snakemake/conda/*.yaml | sed s/\.yaml//) Rscript install.R
+RUN mamba run -p $(grep -rl "R-ODAF_reports" .snakemake/conda/*.yaml | sed s/\.yaml//) Rscript install.R 
+RUN mamba install conda-pack 
+RUN ./scripts/utilities/pack_envs.sh && ls >&2
+RUN rm -rf ./.snakemake/conda
 
 # Final cleanup stage using Debian slim image
-FROM alpine:3.19.1
-#debian:stable-slim
+# Final cleanup stage using Debian slim image
+FROM debian:stable-slim
 
 USER root
 # Install runtime dependencies that are necessary for your application
-RUN apk update \
-      && apk add --no-cache bash su-exec \
-      && rm -rf /var/cache/apk/* \
+RUN apt-get update \
+      && apt-get install -y --no-install-recommends bash gosu wget \
+      && gosu nobody true \
+      && rm -rf /var/lib/apt/lists/* \
+      && apt-get clean \
       && df -h
 
-# Create a user for running; -s sets default shell, -D creates a system user
-RUN adduser -D -s /bin/bash R-ODAF
+# Create a user for running; -m creates home directory, -s sets default shell
+RUN useradd -ms /bin/bash R-ODAF
 
 COPY --from=base /home/R-ODAF /home/R-ODAF
+COPY --from=base /usr/local/bin /usr/local/bin
 COPY --from=base /opt/conda /opt/conda
+COPY --from=base /usr/bin /usr/bin
 
 # Set the working directory and user
 WORKDIR /home/R-ODAF/R-ODAF_Health_Canada
@@ -53,12 +59,12 @@ USER R-ODAF
 # Run tests
 ARG BUILD_CORES=8
 # Add conda to the system path
+RUN ./scripts/utilities/unpack_envs.sh && ls >&2
 ENV PATH="/opt/conda/bin:${PATH}"
 ENV PATH="/opt/conda/envs/snakemake/condabin/:${PATH}"
-RUN . /opt/conda/etc/profile.d/conda.sh && \
-    conda activate snakemake && \
-    snakemake --cores ${BUILD_CORES} --software-deployment-method conda && \
-    df -h
+RUN /opt/conda/envs/snakemake/bin/activate && \
+   /opt/conda/envs/snakemake/bin/snakemake --cores ${BUILD_CORES} --software-deployment-method conda && \
+   df -h
 
 USER root
 # Set the entrypoint for the container
